### ISSUE TITLE
"Report a bug" still untranslated

### ISSUE THREAD

**Issue by Flohack74** [ubports/indicator-session#31]
The string "Report a bug" is still untranslated and also no in the pot file. Regeneration is needed.

**Comment by dobey** [comment]
It is translated and in the translation template already… at least on the `xenial` branch.

However some locales are missing translations for it. If the string is not showing up in weblate, then perhpas there is a configuration issue or bug in weblate itself.

**Comment by Flohack74** [comment]
Well thats interesting it is translated in German:
![grafik](https://user-images.githubusercontent.com/16186470/150768832-bfab254a-525f-4ded-8187-fa1f2d052d4f.png)

And its also in the right branch:
![grafik](https://user-images.githubusercontent.com/16186470/150768918-e9b1d471-b8c6-46a4-989a-b342c9dba568.png)

But it seems not to be in source code repo. Will have a look how this can be.

**Comment by Flohack74** [comment]
Ok it helps when PR gets merged lol
![grafik](https://user-images.githubusercontent.com/16186470/150769290-0417e9e8-2ec7-4f56-8dcf-ad4cc1a8f7c3.png)
