### ISSUE TITLE
Indicator menu -> System -> wrong entry ?

### ISSUE THREAD

**Issue by lutin11** [ubports/indicator-session#8]
Device: Nexus 5
Chanel: stable and devel

I'm not sure this is wondered or not, but under the indicator menu -> Syestem I've got 5 list items
- About this device...
- Ubuntu Help....
- System Settings...
- Lock
- Shutdown...

Instead of 'Ubuntu Help...', that redirect to the Ubuntu Forum, I would expect to have an 'Ubport Help' (or Lorimi Help)

**Comment by ghost** [comment]
I think this bug report can be closed now as the UBports Help... (Aide concernant UBports...) is pointing to the UBports forum.
Regarding the "Report a bug" untranslated string, I proposed a fix here: https://github.com/ubports/indicator-session/pull/11
